---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linode-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: {{ ip_address }}
  share: {{ share_path }}


# kubectl patch storageclass linode-nfs -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'